/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DebateRouteImport } from './routes/debate'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as ConstellationRouteImport } from './routes/constellation'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSlugRouteImport } from './routes/chat.$slug'
import { Route as ApiTtsRouteImport } from './routes/api/tts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateRoute = DebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationRoute = ConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSlugRoute = ChatSlugRouteImport.update({
  id: '/chat/$slug',
  path: '/chat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/council': typeof CouncilRoute
  '/create': typeof CreateRoute
  '/debate': typeof DebateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/council': typeof CouncilRoute
  '/create': typeof CreateRoute
  '/debate': typeof DebateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/codex': typeof CodexRoute
  '/constellation': typeof ConstellationRoute
  '/council': typeof CouncilRoute
  '/create': typeof CreateRoute
  '/debate': typeof DebateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$slug': typeof ChatSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/codex'
    | '/constellation'
    | '/council'
    | '/create'
    | '/debate'
    | '/sitemap.xml'
    | '/api/tts'
    | '/chat/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/codex'
    | '/constellation'
    | '/council'
    | '/create'
    | '/debate'
    | '/sitemap.xml'
    | '/api/tts'
    | '/chat/$slug'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/codex'
    | '/constellation'
    | '/council'
    | '/create'
    | '/debate'
    | '/sitemap.xml'
    | '/api/tts'
    | '/chat/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CodexRoute: typeof CodexRoute
  ConstellationRoute: typeof ConstellationRoute
  CouncilRoute: typeof CouncilRoute
  CreateRoute: typeof CreateRoute
  DebateRoute: typeof DebateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ChatSlugRoute: typeof ChatSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellation': {
      id: '/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof ConstellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$slug': {
      id: '/chat/$slug'
      path: '/chat/$slug'
      fullPath: '/chat/$slug'
      preLoaderRoute: typeof ChatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CodexRoute: CodexRoute,
  ConstellationRoute: ConstellationRoute,
  CouncilRoute: CouncilRoute,
  CreateRoute: CreateRoute,
  DebateRoute: DebateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTtsRoute: ApiTtsRoute,
  ChatSlugRoute: ChatSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
